name: GitHub Actions Sample 4
on:
 issues:
  types: [opened]
jobs:
 Explore-GitHub-Actions:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    configuration: [development, staging, production]
  steps:
  - run: echo "🔧Building the configuration ${{ matrix.configuration }}."
