name: Terraform Plan
on:
  pull_request:
    branches: [ main ]
  push:
    paths:
     - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    steps:
    # Checkout the repository to the GitHub Actions runner
    - uses: actions/checkout@v2
      with:
        terraform_version: 1.1.7
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -no-color
    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate -no-color